### ISSUE TITLE
Block palette dosent open when making a new sprite

### ISSUE THREAD

**Issue by Rubiidev-18** [thepython555/DumosGameMaker#1]
### Expected Behavior

When creating a new sprite, the Block palette should open up

### Actual Behavior

It doesn't.

### Steps to Reproduce

Go into the game engine, create a new sprite, then go back and try to open up a block category

## Steps to reproduce the behavior:
1. Go Into the game maker
2. Create a sprite with whatever
3. Go back
4. try to open a block category

### System Details

Using The Lastest Chrome Version on Android 14.

(yes I copied the issue template from scratch-gui)

**Comment by dumorando** [comment]
just change the size of the window. and its not compatible with mobile, i might remove support for it once i get my stuff back.
